@baseUrl=https://pwp1jfaysk.execute-api.us-east-1.amazonaws.com/

###
POST {{baseUrl}}/notes
Content-Type: application/json

{
  "content": "This is a sample note content.",
  "tags": ["example", "note"],
  "sender":"edu",
  "shouldExpire": true
}